name: Taski Docker Workflow

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.10
        env:
          POSTGRES_USER: dablek
          POSTGRES_PASSWORD: lol425463
          POSTGRES_DB: taski_docker
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-Python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.8.0
          pip install -r backend/requirements.txt
      - name: Lint with ruff
        env:
          POSTGRES_USER: dablek
          POSTGRES_PASSWORD: lol425463
          POSTGRES_DB: taski_docker
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
        run: |
          python -m ruff check backend/
          cd backend/
          python manage.py test
